// Package crypto ports the AES and Kwik helpers of the frozen Python
// original (anicli-py anicli/core/crypto.py) onto the Go standard library.
//
// Divergences from the Python original are deliberate and documented on
// each function; everything else is bug-compatible by design, verified
// against goldens generated by running the Python logic verbatim.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
)

// Errors returned by this package. Callers classify with errors.Is.
var (
	// ErrBadKeyLength: AES key is not 16, 24 or 32 bytes long.
	ErrBadKeyLength = errors.New("aes: key must be 16, 24 or 32 bytes")
	// ErrBadIVLength: CBC initialization vector is not 16 bytes long.
	ErrBadIVLength = errors.New("aes: iv must be 16 bytes")
	// ErrNotBlockAligned: CBC ciphertext length is not a multiple of 16.
	ErrNotBlockAligned = errors.New("aes: ciphertext not block aligned")
	// ErrBadPadding: PKCS7 padding byte out of range or inconsistent.
	ErrBadPadding = errors.New("aes: bad pkcs7 padding")
)

// controlCharStrip mirrors python's CONTROL_CHAR_STRIP = bytes(range(0, 17)):
// bytes 0x00..=0x10 stripped from both ends of decrypted payloads (the
// python implementation relies on this to remove PKCS7 padding; we unpad
// properly first and strip for behavioral parity).
func isControlByte(r rune) bool { return r <= 0x10 }

// pkcs7Pad appends PKCS7 padding for the 16-byte AES block size.
func pkcs7Pad(data []byte) []byte {
	n := aes.BlockSize - len(data)%aes.BlockSize
	padded := make([]byte, len(data)+n)
	copy(padded, data)
	for i := len(data); i < len(padded); i++ {
		padded[i] = byte(n)
	}
	return padded
}

// pkcs7Unpad validates and strips PKCS7 padding. Unlike the python
// original (which silently strips control bytes), malformed padding is a
// loud error.
func pkcs7Unpad(data []byte) ([]byte, error) {
	if len(data) == 0 || len(data)%aes.BlockSize != 0 {
		return nil, ErrNotBlockAligned
	}
	n := int(data[len(data)-1])
	if n == 0 || n > aes.BlockSize || n > len(data) {
		return nil, fmt.Errorf("%w: pad byte %d", ErrBadPadding, n)
	}
	for _, b := range data[len(data)-n:] {
		if int(b) != n {
			return nil, fmt.Errorf("%w: inconsistent pad byte %d, want %d", ErrBadPadding, b, n)
		}
	}
	return data[:len(data)-n], nil
}

// AESEncrypt encrypts plaintext with AES-CBC and PKCS7 padding and returns
// the Base64 (standard) encoded ciphertext. Port of python aes_encrypt.
func AESEncrypt(plaintext string, key, iv []byte) (string, error) {
	block, err := newCBC(key, iv)
	if err != nil {
		return "", err
	}
	padded := pkcs7Pad([]byte(plaintext))
	encrypted := make([]byte, len(padded))
	cipher.NewCBCEncrypter(block, iv).CryptBlocks(encrypted, padded)
	return base64.StdEncoding.EncodeToString(encrypted), nil
}

// AESDecrypt decodes and decrypts Base64-encoded AES-CBC ciphertext.
// Port of python aes_decrypt with two deliberate differences:
//   - PKCS7 padding is validated and stripped loudly (python masked
//     padding errors via control-byte stripping);
//   - bytes 0x00..=0x10 are stripped from both ends afterwards, matching
//     python's .strip(CONTROL_CHAR_STRIP), and invalid UTF-8 sequences are
//     dropped, matching decode("utf-8", errors="ignore").
func AESDecrypt(data string, key, iv []byte) (string, error) {
	block, err := newCBC(key, iv)
	if err != nil {
		return "", err
	}
	raw, err := base64.StdEncoding.DecodeString(data)
	if err != nil {
		return "", fmt.Errorf("aes: decode base64: %w", err)
	}
	if len(raw)%aes.BlockSize != 0 || len(raw) == 0 {
		return "", fmt.Errorf("%w: len %d", ErrNotBlockAligned, len(raw))
	}
	decrypted := make([]byte, len(raw))
	cipher.NewCBCDecrypter(block, iv).CryptBlocks(decrypted, raw)

	unpadded, err := pkcs7Unpad(decrypted)
	if err != nil {
		return "", err
	}
	return strings.ToValidUTF8(strings.TrimFunc(string(unpadded), isControlByte), ""), nil
}

// GCMDecrypt decrypts AES-GCM ciphertext (allanime future use; python had
// no counterpart — the dynamic-AES provider uses GCM tokens). nonce is the
// explicit GCM nonce (12 bytes for the standard construction); the 16-byte
// authentication tag must be the ciphertext tail.
func GCMDecrypt(ciphertext, nonce, key []byte) ([]byte, error) {
	if len(key) != 16 && len(key) != 24 && len(key) != 32 {
		return nil, ErrBadKeyLength
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes: new cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("aes: new gcm: %w", err)
	}
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("aes: gcm open: %w", err)
	}
	return plaintext, nil
}

// ConstantTimeEqual compares two byte slices in constant time; use it
// wherever secret-derived values are compared.
func ConstantTimeEqual(a, b []byte) bool {
	return subtle.ConstantTimeCompare(a, b) == 1
}

// newCBC validates key/iv lengths and returns the cipher block.
func newCBC(key, iv []byte) (cipher.Block, error) {
	if len(key) != 16 && len(key) != 24 && len(key) != 32 {
		return nil, ErrBadKeyLength
	}
	if len(iv) != aes.BlockSize {
		return nil, ErrBadIVLength
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("aes: new cipher: %w", err)
	}
	return block, nil
}
