package api

import (
	"strings"
	"testing"
	"time"
)

// Vectors generated by the reference Python implementation
// (hashlib.pbkdf2_hmac, base64.urlsafe_b64encode without padding) so the
// Go verify function must interoperate with existing anicli-py
// settings.toml hashes verbatim.
const (
	pyVector1Hash     = "pbkdf2_sha256$240000$uE0qBHS22YmdwZyQyeio4w$L17pdSzHKbUXDkb-itZUhRVltIcfhCRrSQJHLmCKLbM"
	pyVector1Password = "correct horse battery staple"

	pyVector2Hash     = "pbkdf2_sha256$120000$g6X6shLqMc4YnTK2_GrY3A$Z2XDqxTZZ9JCiXledc_Ho4o8f0Cq3q0A4eXtF7HKgNM"
	pyVector2Password = "пароль с юникодом ✓"
)

func TestVerifyPasswordHashPythonVectors(t *testing.T) {
	if !VerifyPasswordHash(pyVector1Password, pyVector1Hash) {
		t.Error("vector 1 (ascii, 240000 iters) must verify")
	}
	if !VerifyPasswordHash(pyVector2Password, pyVector2Hash) {
		t.Error("vector 2 (unicode, 120000 iters) must verify")
	}
	if VerifyPasswordHash("wrong password", pyVector1Hash) {
		t.Error("wrong password must fail")
	}
	if VerifyPasswordHash(pyVector1Password, pyVector2Hash) {
		t.Error("cross-vector mismatch must fail")
	}
}

func TestVerifyPasswordHashMalformed(t *testing.T) {
	cases := []string{
		"",
		"plaintext",
		"bcrypt$12$abc$def",
		"pbkdf2_sha256$notanumber$abc$def",
		"pbkdf2_sha256$100$!!!not-base64!!!$def",
		"pbkdf2_sha256$100$abc$!!!not-base64!!!",
		"pbkdf2_sha256$100$abc",                // too few parts
		"pbkdf2_sha256$100$abc$def$extra$more", // too many parts
	}
	for _, hash := range cases {
		if VerifyPasswordHash("x", hash) {
			t.Errorf("malformed hash %q must not verify", hash)
		}
	}
}

func TestAccessTokenRoundTrip(t *testing.T) {
	secret := []byte("test-secret")
	now := time.Date(2026, 9, 13, 12, 0, 0, 0, time.UTC)

	token := IssueAccessToken(secret, "alice", "sid123", 15*time.Minute, now)

	claims, err := DecodeAccessToken(secret, token, now.Add(time.Minute))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if claims.Subject != "alice" || claims.SessionID != "sid123" {
		t.Fatalf("claims mismatch: %+v", claims)
	}
	if claims.TokenType != "access" {
		t.Fatalf("typ = %q, want access", claims.TokenType)
	}
	if want := now.Add(15 * time.Minute).Unix(); claims.ExpiresAt != want {
		t.Fatalf("exp = %d, want %d", claims.ExpiresAt, want)
	}
	if claims.IssuedAt != now.Unix() {
		t.Fatalf("iat = %d, want %d", claims.IssuedAt, now.Unix())
	}
}

func TestAccessTokenExpiry(t *testing.T) {
	secret := []byte("test-secret")
	now := time.Date(2026, 9, 13, 12, 0, 0, 0, time.UTC)
	token := IssueAccessToken(secret, "alice", "sid123", 15*time.Minute, now)

	// Exactly at exp: python checks exp <= now -> expired (inclusive).
	if _, err := DecodeAccessToken(secret, token, now.Add(15*time.Minute)); err == nil {
		t.Fatal("token at exp boundary must be rejected (python: exp <= now)")
	}
	if _, err := DecodeAccessToken(secret, token, now.Add(16*time.Minute)); err == nil {
		t.Fatal("expired token must be rejected")
	}
}

func TestAccessTokenTamperAndFormat(t *testing.T) {
	secret := []byte("test-secret")
	now := time.Now().UTC()
	token := IssueAccessToken(secret, "alice", "sid123", time.Minute, now)

	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		t.Fatalf("token must be header.payload.signature, got %d parts", len(parts))
	}

	if _, err := DecodeAccessToken(secret, "not-a-jwt", now); err == nil {
		t.Fatal("malformed token must be rejected")
	}

	// Forged signature.
	forged := parts[0] + "." + parts[1] + "." + padB64("AAAA")
	if _, err := DecodeAccessToken(secret, forged, now); err == nil {
		t.Fatal("forged signature must be rejected")
	}

	// Wrong secret.
	if _, err := DecodeAccessToken([]byte("other-secret"), token, now); err == nil {
		t.Fatal("wrong secret must be rejected")
	}

	// Tampered payload (claims rewritten, signature stale).
	tampered := parts[0] + "." + padB64(b64Encode([]byte(`{"sub":"eve","sid":"s","exp":9999999999,"iat":1,"typ":"access"}`))) + "." + parts[2]
	if _, err := DecodeAccessToken(secret, tampered, now); err == nil {
		t.Fatal("tampered payload must be rejected")
	}
}

func TestRefreshTokenShape(t *testing.T) {
	tok, err := NewRefreshToken()
	if err != nil {
		t.Fatalf("new refresh token: %v", err)
	}
	// python secrets.token_urlsafe(48) -> 64 unpadded url-safe chars.
	if len(tok) != 64 {
		t.Fatalf("refresh token length = %d, want 64", len(tok))
	}
	tok2, _ := NewRefreshToken()
	if tok == tok2 {
		t.Fatal("refresh tokens must be unique")
	}
	if strings.ContainsAny(tok, "+/") {
		t.Fatal("refresh token must be url-safe")
	}

	h := HashRefreshToken(tok)
	if len(h) != 64 { // sha256 hex
		t.Fatalf("refresh hash length = %d, want 64 hex chars", len(h))
	}
	if HashRefreshToken(tok) != h {
		t.Fatal("refresh hash must be deterministic")
	}
}

// padB64 re-pads a truncated signature body for tamper tests.
func padB64(s string) string {
	for len(s)%4 != 0 {
		s += "="
	}
	return s
}

// b64Encode is the unpadded url-safe encoding used by tokens.
func b64Encode(b []byte) string { return base64URLEncode(b) }
