package providers

import (
	"encoding/json"
	"testing"

	"github.com/an0nx/anicli-go/internal/contracts"
)

// TestAllAnimeSimilarityOracle pins the difflib port against golden ratios
// generated by running Python's difflib.SequenceMatcher(None, a, b).ratio()
// verbatim (testdata/allanime_oracle.json, generator frozen in PR6 report).
// Python's search sort reorders observable results, so the ratio must be
// bug-compatible, including autojunk on strings >= 200 runes.
func TestAllAnimeSimilarityOracle(t *testing.T) {
	t.Parallel()

	var oracle struct {
		Ratios []struct {
			A     string  `json:"a"`
			B     string  `json:"b"`
			Ratio float64 `json:"ratio"`
		} `json:"ratios"`
	}
	if err := json.Unmarshal(fixture(t, "allanime_oracle.json"), &oracle); err != nil {
		t.Fatalf("decode oracle: %v", err)
	}
	if len(oracle.Ratios) == 0 {
		t.Fatal("oracle has no ratio vectors")
	}
	for _, tc := range oracle.Ratios {
		if got := allanimeSimilarity(tc.A, tc.B); got != tc.Ratio {
			t.Errorf("allanimeSimilarity(%q, %q) = %v, want %v", tc.A, tc.B, got, tc.Ratio)
		}
	}
}

// TestAllAnimeSortBySimilarity pins the Python sort key: ratio of
// (query.lower(), title.lower()), descending, stable on ties
// (allanime.py:109-113).
func TestAllAnimeSortBySimilarity(t *testing.T) {
	t.Parallel()

	results := []contracts.SearchResult{
		{Title: "Naruto Shippuden", URL: "a"},
		{Title: "naruto", URL: "b"},
		{Title: "Boruto", URL: "c"},
		{Title: "naruto the movie", URL: "d"},
	}
	sortAllAnimeBySimilarity("naruto", results)

	// Python ratios (oracle): naruto 1.0, Boruto 0.667, then a 0.545 tie
	// between "Naruto Shippuden" and "naruto the movie" — the tie keeps
	// input order (stable sort with reverse=True).
	want := []string{"b", "c", "a", "d"}
	for i, id := range want {
		if results[i].URL != id {
			t.Fatalf("sorted[%d].URL = %s, want %s", i, results[i].URL, id)
		}
	}
}

// TestAllAnimeSortBySimilarityStable pins stable ordering for equal ratios
// (Python list.sort is stable; a tie must not reorder equal-rank hits).
func TestAllAnimeSortBySimilarityStable(t *testing.T) {
	t.Parallel()

	results := []contracts.SearchResult{
		{Title: "zeta", URL: "0"},
		{Title: "beta", URL: "1"},
		{Title: "alpha", URL: "2"},
	}
	sortAllAnimeBySimilarity("unrelated query", results)
	for i, id := range []string{"0", "1", "2"} {
		if results[i].URL != id {
			t.Fatalf("tie order changed: got %v", results)
		}
	}
}
