package providers

// Tests for the surviving AllAnime decode helpers (the "--" URL
// decoder and the tobeparsed decrypt paths). Pure-crypto goldens live
// in allanime_proto_test.go; bootstrap/material tests in
// allanime_bootstrap_test.go.

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"testing"
)

// aaTestKey derives a deterministic 32-byte test key.
func aaTestKey(seed byte) []byte {
	b := make([]byte, 32)
	for i := range b {
		b[i] = seed + byte(i)*3
	}
	return b
}

// aaSealBlob seals plain with AES-256-GCM into the 0x01|iv|ct||tag
// framing (test-side oracle, fixed iv).
func aaSealBlob(t *testing.T, key []byte, plain string) string {
	t.Helper()
	iv := make([]byte, 12)
	for i := range iv {
		iv[i] = byte(i + 1)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		t.Fatal(err)
	}
	sealed := gcm.Seal(nil, iv, []byte(plain), nil)
	out := append([]byte{0x01}, iv...)
	out = append(out, sealed...)
	return base64.StdEncoding.EncodeToString(out)
}

// TestAADecryptRoundTrip feeds a blob sealed with the material key and
// expects the decrypted sourceUrls with the "--" prefix trimmed (both
// the bare and data-wrapped plaintext shapes).
func TestAADecryptRoundTrip(t *testing.T) {
	t.Parallel()

	key := aaTestKey(11)
	for _, plain := range []string{
		`{"data":{"episode":{"episodeString":"1","sourceUrls":[` +
			`{"sourceUrl":"--0805171b060c2f08051b3f","sourceName":"S-mp4"},` +
			`{"sourceUrl":"https://cdn.example/v.mp4","sourceName":"Yt-mp4"}]}}}`,
		`{"episode":{"episodeString":"1","sourceUrls":[` +
			`{"sourceUrl":"--0805171b060c2f08051b3f","sourceName":"S-mp4"},` +
			`{"sourceUrl":"https://cdn.example/v.mp4","sourceName":"Yt-mp4"}]}}`,
	} {
		sources, err := aaDecryptToBeParsed(aaSealBlob(t, key, plain), key)
		if err != nil {
			t.Fatalf("decrypt %s: %v", plain[:20], err)
		}
		if len(sources) != 2 {
			t.Fatalf("sources = %d, want 2 (%+v)", len(sources), sources)
		}
		if sources[0].Name != "S-mp4" || sources[0].URL != "0805171b060c2f08051b3f" {
			t.Errorf("source[0] = %+v, want trimmed -- prefix", sources[0])
		}
		if sources[1].Name != "Yt-mp4" || sources[1].URL != "https://cdn.example/v.mp4" {
			t.Errorf("source[1] = %+v", sources[1])
		}
	}
}

// TestAADecryptEncodings accepts URL-safe alphabets too.
func TestAADecryptEncodings(t *testing.T) {
	t.Parallel()

	key := aaTestKey(5)
	plain := `{"episode":{"sourceUrls":[{"sourceUrl":"--ab","sourceName":"x"}]}}`
	std := aaSealBlob(t, key, plain)

	if _, err := aaDecryptToBeParsed(std, key); err != nil {
		t.Fatalf("std base64 rejected: %v", err)
	}
	raw, err := base64.StdEncoding.DecodeString(std)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := aaDecryptToBeParsed(base64.URLEncoding.EncodeToString(raw), key); err != nil {
		t.Fatalf("url-safe base64 rejected: %v", err)
	}
}

func TestAADecryptFailures(t *testing.T) {
	t.Parallel()

	key := aaTestKey(9)
	plain := `{"episode":{"sourceUrls":[{"sourceUrl":"--ab","sourceName":"x"}]}}`

	if _, err := aaDecryptToBeParsed("not base64 !!!", key); err == nil {
		t.Error("garbage base64 accepted")
	}
	if _, err := aaDecryptToBeParsed(base64.StdEncoding.EncodeToString([]byte{0x01, 0x02}), key); err == nil {
		t.Error("short blob accepted")
	}
	if _, err := aaDecryptToBeParsed(aaSealBlob(t, aaTestKey(10), plain), key); err == nil {
		t.Error("wrong-key blob accepted, want GCM auth failure")
	}

	// Valid encryption, no sources inside: loud, not a silent empty set.
	if _, err := aaDecryptToBeParsed(aaSealBlob(t, key, `{"episode":{}}`), key); err == nil {
		t.Error("source-less payload accepted")
	}
}

// TestAADecryptRegexFallback pins the fallback extraction when the
// plaintext is not clean JSON (upstream keeps a regex fallback for
// exactly this case).
func TestAADecryptRegexFallback(t *testing.T) {
	t.Parallel()

	key := aaTestKey(13)
	plain := `prefix junk {"sourceUrl":"--deadbeef","sourceName":"Luf-Mp4"} trailing`
	sources, err := aaDecryptToBeParsed(aaSealBlob(t, key, plain), key)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if len(sources) != 1 || sources[0].Name != "Luf-Mp4" || sources[0].URL != "deadbeef" {
		t.Fatalf("sources = %+v, want regex-extracted Luf-Mp4", sources)
	}
}

// TestAADecodeHexPairsOracle pins the Python _decrypt port
// (allanime.py:273-283: chr(int(hex,16) ^ 56) per pair) against vectors
// generated by running the frozen Python code.
func TestAADecodeHexPairsOracle(t *testing.T) {
	t.Parallel()

	var oracle struct {
		URLDecodes []struct {
			Encoded string `json:"encoded"`
			Want    string `json:"want"`
		} `json:"url_decodes"`
	}
	if err := json.Unmarshal(fixture(t, "allanime_oracle.json"), &oracle); err != nil {
		t.Fatalf("decode oracle: %v", err)
	}
	if len(oracle.URLDecodes) == 0 {
		t.Fatal("oracle has no url vectors")
	}
	for _, tc := range oracle.URLDecodes {
		got, ok := aaDecodeHexPairs(tc.Encoded)
		if !ok {
			t.Errorf("aaDecodeHexPairs(%q) rejected", tc.Encoded)
			continue
		}
		if got != tc.Want {
			t.Errorf("aaDecodeHexPairs(%q) = %q, want %q", tc.Encoded, got, tc.Want)
		}
	}
}

func TestAADecodeHexPairsRejects(t *testing.T) {
	t.Parallel()

	if _, ok := aaDecodeHexPairs("abc"); ok {
		t.Error("odd-length input accepted")
	}
	if _, ok := aaDecodeHexPairs("zz"); ok {
		t.Error("non-hex input accepted")
	}
	if _, ok := aaDecodeHexPairs(""); ok {
		t.Error("empty input accepted")
	}
}

// TestAADecodeSourceURL pins the "--" URL decode + absolutize rules
// (Python parity vectors; encoded bodies built with the exact
// chr(int(hex,16)^56) encoder).
func TestAADecodeSourceURL(t *testing.T) {
	t.Parallel()

	const base = "https://allanime.day"
	enc := func(s string) string {
		out := make([]byte, 0, len(s)*2)
		for _, r := range s {
			out = append(out, []byte(fmt.Sprintf("%02x", int(r)^56))...)
		}
		return string(out)
	}

	if got, ok := decodeAllAnimeSourceURL("--"+enc("/all/manga/clock?w=1"), base); !ok ||
		got != base+"/all/manga/clock.json?w=1" {
		t.Fatalf("internal clock url = %q ok=%v", got, ok)
	}
	if got, ok := decodeAllAnimeSourceURL("--"+enc("https://ext.example/clock?x"), base); !ok ||
		got != "https://ext.example/clock.json?x" {
		t.Fatalf("external url = %q ok=%v", got, ok)
	}
	if got, ok := decodeAllAnimeSourceURL("--"+enc("/getwide/abc.mp4"), base); !ok ||
		got != base+"/getwide/abc.mp4" {
		t.Fatalf("mp4 url = %q ok=%v", got, ok)
	}
	// Plain URLs pass through verbatim (live v3 shape).
	if got, ok := decodeAllAnimeSourceURL("https://plain.example/x.m3u8", base); !ok ||
		got != "https://plain.example/x.m3u8" {
		t.Fatalf("plain url = %q ok=%v", got, ok)
	}
	if got, ok := decodeAllAnimeSourceURL("https://ok.ru/videoembed/1", base); !ok ||
		got != "https://ok.ru/videoembed/1" {
		t.Fatalf("iframe url = %q ok=%v", got, ok)
	}
	// Relative path without leading slash gains "/".
	if got, ok := decodeAllAnimeSourceURL("--"+enc("abc"), base); !ok ||
		got != base+"/abc" {
		t.Fatalf("relative url = %q ok=%v", got, ok)
	}
	// Unmarked non-hex value is a plain relative URL.
	if got, ok := decodeAllAnimeSourceURL("rel/path", base); !ok ||
		got != base+"/rel/path" {
		t.Fatalf("plain relative url = %q ok=%v", got, ok)
	}
	// Empty and malformed bodies are rejected.
	if _, ok := decodeAllAnimeSourceURL("", base); ok {
		t.Fatal("empty accepted")
	}
	if _, ok := decodeAllAnimeSourceURL("--abc", base); ok {
		t.Fatal("malformed hex body accepted")
	}
}

// TestAAIsDirectMedia pins the live direct-media classification:
// type "player" (Yt-mp4 live source), fallBack "mp4" and URLs naming
// media files; iframe embeds without media extensions are not direct.
func TestAAIsDirectMedia(t *testing.T) {
	t.Parallel()

	if !aaIsDirectMedia(aaSource{Type: "player", URL: "https://tools.fast4speed.rsvp/media9/videos/x/sub/1?Authorization=1"}) {
		t.Error("type=player source not classified direct")
	}
	if !aaIsDirectMedia(aaSource{FallBack: "mp4", URL: "https://x/y"}) {
		t.Error("fallBack=mp4 source not classified direct")
	}
	if !aaIsDirectMedia(aaSource{URL: "https://x/v.mp4"}) {
		t.Error(".mp4 URL not classified direct")
	}
	if !aaIsDirectMedia(aaSource{URL: "https://x/v.m3u8"}) {
		t.Error(".m3u8 URL not classified direct")
	}
	if aaIsDirectMedia(aaSource{Type: "iframe", URL: "https://ok.ru/videoembed/1"}) {
		t.Error("iframe embed misclassified as direct media")
	}
}
