package providers

import (
	"encoding/json"
	"testing"
)

// TestSequenceMatcherRatioOracle pins the difflib port against golden
// ratios generated by running Python's
// difflib.SequenceMatcher(None, a, b).ratio() verbatim
// (testdata/sequencematch_oracle.json, generator frozen in the PR6
// report). The matcher reorders observable output (history-rehydration
// matching), so the ratio must be bug-compatible, including autojunk
// on strings >= 200 runes.
func TestSequenceMatcherRatioOracle(t *testing.T) {
	t.Parallel()

	var oracle struct {
		Ratios []struct {
			A     string  `json:"a"`
			B     string  `json:"b"`
			Ratio float64 `json:"ratio"`
		} `json:"ratios"`
	}
	if err := json.Unmarshal(fixture(t, "sequencematch_oracle.json"), &oracle); err != nil {
		t.Fatalf("decode oracle: %v", err)
	}
	if len(oracle.Ratios) == 0 {
		t.Fatal("oracle has no ratio vectors")
	}
	for _, tc := range oracle.Ratios {
		if got := sequenceMatcherRatio(tc.A, tc.B); got != tc.Ratio {
			t.Errorf("sequenceMatcherRatio(%q, %q) = %v, want %v", tc.A, tc.B, got, tc.Ratio)
		}
	}
}
