package providers

import (
	"sort"
)

// This file ports CPython's difflib.SequenceMatcher(None, a, b) matcher
// for the history-rehydration similarity matching (the frozen anicli-py
// reference implementation used the same primitive as its search-sort
// key; the port and its goldens predate the current roster — see the
// PR6 report):
//
//	results.sort(
//	    key=lambda x: difflib.SequenceMatcher(
//	        None, query.lower(), x.title.lower()).ratio(),
//	    reverse=True,
//	)
//
// Python's difflib has no Go counterpart in the standard library and
// the matching reorders observable output, so the matcher is ported
// bug-compatible with CPython's SequenceMatcher (isjunk=None,
// autojunk=True default): b2j index, autojunk purge for len(b) >= 200,
// diagonal j2len longest-match scan, edge extension over non-junk,
// queue-driven block recursion and adjacent-block collapse. The ratio
// goldens in testdata/sequencematch_oracle.json were generated by
// running the Python implementation verbatim (see PR6 report).

// smMatch is one aligned block: a[ai:ai+size] == b[bi:bi+size].
type smMatch struct {
	ai, bi, size int
}

// smMatcher is the mutable matching state over the pattern b (CPython
// keeps it on the SequenceMatcher; only b's index survives here, a is
// passed per call).
type smMatcher struct {
	b     []rune
	b2j   map[rune][]int
	bjunk map[rune]struct{}
}

// newSMMatcher indexes b. isjunk is always nil (Python passed None);
// autojunk stays enabled, matching the SequenceMatcher(None, a, b)
// default in the Python sort key.
func newSMMatcher(b []rune) *smMatcher {
	m := &smMatcher{b: b, b2j: make(map[rune][]int, len(b)), bjunk: map[rune]struct{}{}}
	for i, elt := range b {
		m.b2j[elt] = append(m.b2j[elt], i)
	}
	// CPython autojunk: purge elements occurring more than n//100+1
	// times when len(b) >= 200. Long titles do reach this branch.
	if n := len(b); n >= 200 {
		ntest := n/100 + 1
		for elt, idxs := range m.b2j {
			if len(idxs) > ntest {
				delete(m.b2j, elt)
			}
		}
	}
	return m
}

// findLongestMatch ports CPython find_longest_match over a[alo:ahi] and
// b[blo:bhi]. Scan order (i ascending, j ascending within the index
// list, strict k > bestsize) is load-bearing for which of several
// equal-length matches wins.
func (m *smMatcher) findLongestMatch(a []rune, alo, ahi, blo, bhi int) smMatch {
	besti, bestj, bestsize := alo, blo, 0
	j2len := map[int]int{}
	for i := alo; i < ahi; i++ {
		newj2len := map[int]int{}
		for _, j := range m.b2j[a[i]] {
			if j < blo {
				continue
			}
			if j >= bhi {
				break
			}
			k := j2len[j-1] + 1
			newj2len[j] = k
			if k > bestsize {
				besti, bestj, bestsize = i-k+1, j-k+1, k
			}
		}
		j2len = newj2len
	}

	// Extend the best by non-junk elements on each end (CPython's two
	// extension loops; the junk-clump loops are no-ops with isjunk=None
	// because bjunk is always empty and the non-junk loops already
	// cover every extension reachable without junk).
	isbjunk := func(r rune) bool {
		_, ok := m.bjunk[r]
		return ok
	}
	for besti > alo && bestj > blo &&
		!isbjunk(m.b[bestj-1]) && a[besti-1] == m.b[bestj-1] {
		besti, bestj, bestsize = besti-1, bestj-1, bestsize+1
	}
	for besti+bestsize < ahi && bestj+bestsize < bhi &&
		!isbjunk(m.b[bestj+bestsize]) && a[besti+bestsize] == m.b[bestj+bestsize] {
		bestsize++
	}
	return smMatch{besti, bestj, bestsize}
}

// smMatchingBlocks ports CPython get_matching_blocks: recursive
// longest-match splitting via an explicit queue, then sorting and
// collapsing adjacent blocks, with the trailing (la, lb, 0) sentinel.
func smMatchingBlocks(a, b []rune) []smMatch {
	m := newSMMatcher(b)
	la, lb := len(a), len(b)
	type span struct{ alo, ahi, blo, bhi int }
	queue := []span{{0, la, 0, lb}}
	var blocks []smMatch
	for len(queue) > 0 {
		s := queue[len(queue)-1]
		queue = queue[:len(queue)-1]
		x := m.findLongestMatch(a, s.alo, s.ahi, s.blo, s.bhi)
		if x.size > 0 {
			blocks = append(blocks, x)
			if s.alo < x.ai && s.blo < x.bi {
				queue = append(queue, span{s.alo, x.ai, s.blo, x.bi})
			}
			if x.ai+x.size < s.ahi && x.bi+x.size < s.bhi {
				queue = append(queue, span{x.ai + x.size, s.ahi, x.bi + x.size, s.bhi})
			}
		}
	}
	sort.Slice(blocks, func(i, j int) bool {
		if blocks[i].ai != blocks[j].ai {
			return blocks[i].ai < blocks[j].ai
		}
		if blocks[i].bi != blocks[j].bi {
			return blocks[i].bi < blocks[j].bi
		}
		return blocks[i].size < blocks[j].size
	})

	var collapsed []smMatch
	i1, j1, k1 := 0, 0, 0
	for _, bl := range blocks {
		if i1+k1 == bl.ai && j1+k1 == bl.bi {
			k1 += bl.size
		} else {
			if k1 > 0 {
				collapsed = append(collapsed, smMatch{i1, j1, k1})
			}
			i1, j1, k1 = bl.ai, bl.bi, bl.size
		}
	}
	if k1 > 0 {
		collapsed = append(collapsed, smMatch{i1, j1, k1})
	}
	return append(collapsed, smMatch{la, lb, 0})
}

// sequenceMatcherRatio ports CPython SequenceMatcher(None, a, b).ratio():
// 2*M / (len(a)+len(b)) with M the total matched size, 1.0 when both
// are empty. Operates on runes (Python strings are code points); Go
// strings.ToLower replaces Python str.lower for the callers' lowercased
// inputs (both are Unicode-aware).
func sequenceMatcherRatio(a, b string) float64 {
	ar, br := []rune(a), []rune(b)
	matches := 0
	for _, bl := range smMatchingBlocks(ar, br) {
		matches += bl.size
	}
	length := len(ar) + len(br)
	if length == 0 {
		return 1.0
	}
	return 2 * float64(matches) / float64(length)
}
